version: "3.6"
services:
  movie-api:
    build:
      context: ./
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/movie
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: movie
      POSTGRES_PASSWORD: movie
      POSTGRES_DB: movie
    ports:
      - "5432:5432"