INSERT INTO role (name, description)
VALUES ('ACTOR',
        'Role to identify an individual who plays a character in a film or television show.'),
       ('DIRECTOR',
        'Role to identify the person responsible for making creative decisions and guiding the production of a film or television show.');


INSERT INTO genre (name)
VALUES ('Action'),
       ('Adventure'),
       ('Animated'),
       ('Biography'),
       ('Comedy'),
       ('Crime'),
       ('Dance'),
       ('Disaster'),
       ('Documentary'),
       ('Drama'),
       ('Erotic'),
       ('Family'),
       ('Fantasy'),
       ('Found Footage'),
       ('Historical'),
       ('Horror'),
       ('Independent'),
       ('Legal'),
       ('Live Action'),
       ('Martial Arts'),
       ('Musical'),
       ('Mystery'),
       ('Noir'),
       ('Performance'),
       ('Political'),
       ('Romance'),
       ('Satire'),
       ('Science Fiction'),
       ('Short'),
       ('Silent'),
       ('Slasher'),
       ('Sports'),
       ('Spy'),
       ('Superhero'),
       ('Supernatural'),
       ('Suspense'),
       ('Teen'),
       ('Thriller'),
       ('War'),
       ('Western');
